#!/bin/bash

. /etc/os-release
cat > /etc/issue << "COW"
 ___                    ___   ___ ___
| . | ___    ___ ._ _  | __>| . || __>
| | || . ＼/ ._> | ' | | _> | | ||  _>
``___``||  _/ ＼___.|_|_| |___>|``___``||___>
     |_|  

COW

cat >> /etc/issue << EOF
$PRETTY_NAME
Kernel \r on an \m (\l)

================================================================================
NIC              State          Address
$(ip -br addr show | grep -E -v '^(lo|flannel|cni|veth)')
================================================================================
EOF
cat >> /etc/issue << "EOF"

Welcome to openEOE (login with user: openEOE)
EOF
