#!/bin/bash

. /etc/os-release
cat > /etc/issue << "COW"

                            _____  _____  _____ 
                           |  ___||  _  ||  ___|
  ___   _ __    ___  _ __  | |__  | | | || |__  
 / _ \ | '_ \  / _ \| '_ \ |  __| | | | ||  __| 
| (_) || |_) ||  __/| | | || |___ \ \_/ /| |___ 
 \___/ | .__/  \___||_| |_|\____/  \___/ \____/ 
       | |                                      
       |_|                                      

COW

cat >> /etc/issue << EOF
$PRETTY_NAME
Kernel \r on an \m (\l)

================================================================================
NIC              State          Address
$(ip -br addr show | grep -E -v '^(lo|flannel|cni|veth)')
================================================================================
EOF
cat >> /etc/issue << "EOF"

Welcome to openEOE (login with user: openEOE)
EOF
